# Generated by Django 4.2.3 on 2023-07-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('categoria1', 'Fútbol'), ('categoria2', 'Básquet'), ('categoria3', 'Hockey')], max_length=20),
        ),
    ]
