# Generated by Django 4.2.3 on 2023-07-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_eventocategoria_alter_evento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
